# Generated by Django 5.0.2 on 2024-03-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="updated_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
